title: OpenSource UC | Blog
tagline: Blog y noticias

exclude: [path vendor]

author:
  name: Axel Sepulveda & OpenSource UC
  url: https://github.com/open-source-uc

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  
paginate: 3

remote_theme: zivong/jekyll-theme-hydure

tags_path: /tags/
categories_path: /categories/
