title: OpenSource UC - Blog
tagline: Blog de noticias y contenido

author:
  name: Song-Zi Vong
  url: https://twitter.com/zivong91

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 3

tags_path: /tags/
categories_path: /categories/
